import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import {Providers} from "@/app/providers"
import { ReactNode } from "react"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  return (
    <html lang="en" className="light">
      <Providers>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  )
}
